apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h5zcfl20b-go
  janus-idp.io/tekton: h5zcfl20b-go
  backstage.io/kubernetes-id: h5zcfl20b-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h5zcfl20b-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
